### ISSUE TITLE
Forgotten fireEvents on the test

### ISSUE THREAD

**Issue by ARS-coding** [learn-co-curriculum/react-hooks-fetch-crud-lab#3]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.

## Describe the bug

In App.test.js file, at line 61 and 77 there should be a fireEvent for View Questions" button to be clicked. Currently, because it's not being clicked the questions won't show up and the queries that is being made is gonna return an empty array or null so the tests will faild even the student does all the functionality. But I suggest another, but easier solution which is setting the default value of the state named "page" in App.js to "List" instead of an empty string to not have a blank screen that has just two buttons at the initial rendering of the app.

Write a clear and concise description of what the bug is. Include the file and
line number(s) if possible.

## What is the expected behavior?

Test to be able to query the components.

Write a clear and concise description of what you expected to happen.

## Screenshots

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X
- [ ] WSL
- [x] Linux

## Any additional context?

We had to comment this code which is on line 66 in App.test.js
`await waitForElementToBeRemoved(() => screen.queryByText(/lorem testum 1/g));`

**Comment by ihollander** [comment]
Hi @ARS-coding - thanks for reaching out about this! I'm not sure I understand the second part of your suggestion, the initial state for `page` in App is `"List"`:

https://github.com/learn-co-curriculum/react-hooks-fetch-crud-lab/blob/master/src/components/App.js#L7

Is that what you're referring to for the fix for this issue?

One other suggestion I have when you are running the tests - if you're ever curious about what the DOM looks like when the tests are being run, you can use the [`screen.debug()`](https://testing-library.com/docs/queries/about/#screendebug) method in the test files to get a snapshot printed to the console when your tests run.

**Comment by ARS-coding** [comment]
> Hi @ARS-coding - thanks for reaching out about this! I'm not sure I understand the second part of your suggestion, the initial state for `page` in App is `"List"`:
> 
> https://github.com/learn-co-curriculum/react-hooks-fetch-crud-lab/blob/master/src/components/App.js#L7
> 
> Is that what you're referring to for the fix for this issue?
> 
> One other suggestion I have when you are running the tests - if you're ever curious about what the DOM looks like when the tests are being run, you can use the [`screen.debug()`](https://testing-library.com/docs/queries/about/#screendebug) method in the test files to get a snapshot printed to the console when your tests run.

Unfortunately I don't have much knowledge about testing. But as far as we understood, the problem was DOM was being tested before "View Questions" click event happened, so there should have been a click event before testing the DOM. But another approach could be making the default value of the state named page to be "list" so the UX wouldn't require us to click to the "View Questions" button in order to see the questions and as a result of that we wouldn't need a click event before DOM testing in App.test.js because it would already initially show the questions when App gets rendered. But this error is half of the story, I unfortunately don't know  what was the problem with this "await waitForElementToBeRemoved(() => screen.queryByText(/lorem testum 1/g));" code at line 66 in App.test.js but we took a look at it with our coaches, couldn't figure it out, in order to pass the test we just had to comment it out. I just wanted to point that out at the end and I probably should have explain it more effectively, my bad. 
I wish you a great day, hopefully this was helpful! :)

**Comment by ihollander** [comment]
@ARS-coding I understand your first question a bit better now - I updated the tests to click the "View Questions" button for tests 3 and 4 to ensure the application is in the right state to run those tests. With the starter code having the initial state of "List", clicking that button shouldn't be necessary since the application is already in the correct state, but it doesn't hurt to add it 😄 

Regarding this line in the tests:

```js
await waitForElementToBeRemoved(() => screen.queryByText(/lorem testum 1/g));
```

What this does is wait for the screen to be updated by some asynchronous action before running the rest of the code below. In this case, it's expecting that when the "Delete Question" button is clicked, the question element will be removed from the page **after** the fetch request is completed. Then it continues running the rest of the test code to check that the element is not on the page after re-rendering the App component.

Hope this is helpful!
